Gem::Specification.new do |s|
  s.name = "innate"
  s.version = "2009.02.21"

  s.summary = "Powerful web-framework wrapper for Rack."
  s.description = "Simple, straight-forward, base for web-frameworks."
  s.platform = "ruby"
  s.has_rdoc = true
  s.author = "Michael 'manveru' Fellinger"
  s.email = "m.fellinger@gmail.com"
  s.homepage = "http://github.com/manveru/innate"
  s.require_path = "lib"

  s.add_dependency('rack', '>= 0.4.0')

  s.files = [
    "CHANGELOG",
    "COPYING",
    "MANIFEST",
    "README.md",
    "Rakefile",
    "example/app/retro_games.rb",
    "example/app/whywiki_erb/layout/wiki.html.erb",
    "example/app/whywiki_erb/spec/wiki.rb",
    "example/app/whywiki_erb/start.rb",
    "example/app/whywiki_erb/view/edit.html.erb",
    "example/app/whywiki_erb/view/index.html.erb",
    "example/custom_middleware.rb",
    "example/error_handling.rb",
    "example/hello.rb",
    "example/howto_spec.rb",
    "example/link.rb",
    "example/providing_hash.rb",
    "example/session.rb",
    "innate.gemspec",
    "lib/innate.rb",
    "lib/innate/action.rb",
    "lib/innate/adapter.rb",
    "lib/innate/cache.rb",
    "lib/innate/cache/api.rb",
    "lib/innate/cache/drb.rb",
    "lib/innate/cache/file_based.rb",
    "lib/innate/cache/marshal.rb",
    "lib/innate/cache/memory.rb",
    "lib/innate/cache/yaml.rb",
    "lib/innate/core_compatibility/basic_object.rb",
    "lib/innate/core_compatibility/string.rb",
    "lib/innate/current.rb",
    "lib/innate/dynamap.rb",
    "lib/innate/helper.rb",
    "lib/innate/helper/aspect.rb",
    "lib/innate/helper/cgi.rb",
    "lib/innate/helper/flash.rb",
    "lib/innate/helper/link.rb",
    "lib/innate/helper/partial.rb",
    "lib/innate/helper/redirect.rb",
    "lib/innate/helper/send_file.rb",
    "lib/innate/log.rb",
    "lib/innate/log/color_formatter.rb",
    "lib/innate/log/hub.rb",
    "lib/innate/mock.rb",
    "lib/innate/node.rb",
    "lib/innate/options.rb",
    "lib/innate/options/dsl.rb",
    "lib/innate/request.rb",
    "lib/innate/response.rb",
    "lib/innate/route.rb",
    "lib/innate/session.rb",
    "lib/innate/session/flash.rb",
    "lib/innate/setup.rb",
    "lib/innate/spec.rb",
    "lib/innate/state.rb",
    "lib/innate/state/accessor.rb",
    "lib/innate/state/fiber.rb",
    "lib/innate/state/thread.rb",
    "lib/innate/traited.rb",
    "lib/innate/trinity.rb",
    "lib/innate/version.rb",
    "lib/innate/view.rb",
    "lib/innate/view/erb.rb",
    "lib/innate/view/none.rb",
    "lib/rack/middleware_compiler.rb",
    "lib/rack/reloader.rb",
    "spec/example/hello.rb",
    "spec/example/link.rb",
    "spec/helper.rb",
    "spec/innate/action/layout.rb",
    "spec/innate/action/layout/file_layout.erb",
    "spec/innate/cache/common.rb",
    "spec/innate/cache/marshal.rb",
    "spec/innate/cache/memory.rb",
    "spec/innate/cache/yaml.rb",
    "spec/innate/dynamap.rb",
    "spec/innate/helper.rb",
    "spec/innate/helper/aspect.rb",
    "spec/innate/helper/cgi.rb",
    "spec/innate/helper/flash.rb",
    "spec/innate/helper/link.rb",
    "spec/innate/helper/partial.rb",
    "spec/innate/helper/redirect.rb",
    "spec/innate/helper/send_file.rb",
    "spec/innate/helper/view/aspect_hello.erb",
    "spec/innate/helper/view/locals.erb",
    "spec/innate/helper/view/loop.erb",
    "spec/innate/helper/view/num.erb",
    "spec/innate/helper/view/partial.erb",
    "spec/innate/helper/view/recursive.erb",
    "spec/innate/mock.rb",
    "spec/innate/node.rb",
    "spec/innate/node/another_layout/another_layout.erb",
    "spec/innate/node/bar.html",
    "spec/innate/node/foo.html.erb",
    "spec/innate/node/with_layout.erb",
    "spec/innate/options.rb",
    "spec/innate/parameter.rb",
    "spec/innate/request.rb",
    "spec/innate/route.rb",
    "spec/innate/session.rb",
    "spec/innate/traited.rb"
  ]
end
